env:
  global:
  - USER=bitnami
  - HOST=ec2-52-35-76-230.us-west-2.compute.amazonaws.com
languages: node_js
branches:
  only: master
before_install:
- openssl aes-256-cbc -K $encrypted_7a52f27f0ced_key -iv $encrypted_7a52f27f0ced_iv
  -in resources/realmshaper.pem.enc -out resources/realmshaper.pem -d
install:
- npm install
before_script:
- echo -e "Host $HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: gulp
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 resources/realmshaper.pem
- ssh-add resources/realmshaper.pem
- git remote add live ssh://$USER@$HOST/home/bitnami/apps/worldshaper.git
- git push -f live master
