env:
  global:
  - USER=bitnami
  - HOST=ec2-52-35-76-230.us-west-2.compute.amazonaws.com
languages: node_js
branches:
  only: master
before_install:
- openssl aes-256-cbc -K $encrypted_7a52f27f0ced_key -iv $encrypted_7a52f27f0ced_iv
  -in resources/realmshaper.pem.enc -out resources/realmshaper.pem -d
install:
- npm install
before_script:
- echo -e "Host $HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: gulp
after_script: gulp prod
deploy:
  provider: s3
  access_key_id: AKIAJJS4DOZOSWWT5ZVA
  secret_access_key:
    secure: ccvlOxhmNuyXGGQ3x1hAHjiTHtW92NO7AIXWjTQHz7JG5R1QGreBYnGxsaBiTPCKpZm1oUthCqaoVId9XoDMYn2GCtmuL1lre6plCZnrFjuCJHFSpfY9RPsq6NMGAJzW7CabZ7UHpj37P+33i7JaZHJsGgOMWvC9myuAeNsvUGpXujpCvIS5UGFfJLutaSYgKrpF1cSw3q8r6iJ/sJVC/MGo/QmaxP1zaHa1zxyFXEuNobD151CAcbCzj+ocylJ8T2i28qkGAwmQFAPzx+yu5UMbWEteMdvfImSSXiPT0vh1+SZVTTiAyfXk/wJQS2Q4gmnrQ8b53OruftBdee9Rv6nBtjgc0CMgLld4v1pauNs4gPcQImd7SinRRDsn1xJk8HtTBdV8HTxbk4UCKW/fzQBOyP8zE1MZQgCiiu6wXCiUdIBMQlqWvLnMppwEdIu1g4UbdILeRGtQ9rTqiDqbT6a+G3IY/ZVp0BhugrrQrQe73XpJajCixtmFCz+8Dko4ZJKvPjSVS5twTEujpX9EDFWEZCqGib6eu7M4oWPL7Nw/+7/cobfWY22KJPK2tkW/It6QyCYyVTjNuq8G6lYyfcemwTwi8W4DE6PkzkGso+Zf/5hidKxx8B8hDZTBvf/EtFcmP1GeEIjh/r9szfg0tOfyF+wsUuwGlRtNWwDUC5k=
  bucket: "realmshaper.com"
  skip_cleanup: true
  local_dir: dist
